### ISSUE TITLE
[helm/mongodb] Mongo replica set not established after restarting mongo cluster 

### ISSUE THREAD

**Issue by euan-tilley** [bitnami/bitnami-docker-mongodb#110]
**Description**
We have some scenarios when we need to test reinstalling our app from scratch without deleteing mongo data, so when running a test I came across this issue.
After running a helm install then a helm delete (pvc left BOUND) then rerunning a helm install the replica set does not seem to get reconfigured correctly.

**Steps to reproduce the issue:**

1. curl -O https://raw.githubusercontent.com/kubernetes/charts/master/stable/mongodb/values-production.yaml
helm install --name my-release -f ./values-production.yaml stable/mongodb --set mongodbRootPassword=password
2. helm del --purge my-release
3. helm install --name my-release -f ./values-production.yaml stable/mongodb --set mongodbRootPassword=password

**Describe the results you received:**
After installing the chart the first time the replica set gets configured correctly & everything is good. When installing the second time the replica set does not get configured corectly & the below log is written

```
Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues

nami    INFO  Initializing mongodb
mongodb INFO  ==> Deploying MongoDB with persisted data...
mongodb INFO  ==> No injected configuration files found. Creating default config files...
mongodb INFO  ==> Writing keyfile for replica set authentication
mongodb INFO  ==> Enabling MongoDB replica set mode
mongodb INFO
mongodb INFO  ########################################################################
mongodb INFO   Installation parameters for mongodb:
mongodb INFO     Persisted data and properties have been restored.
mongodb INFO     Any input specified will not take effect.
mongodb INFO   This installation requires no credentials.
mongodb INFO  ########################################################################
mongodb INFO
nami    INFO  mongodb successfully initialized
INFO  ==> Starting mongodb...
INFO  ==> Starting mongod...
2018-08-30T19:58:40.009+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2018-08-30T19:58:40.027+0000 I CONTROL  [initandlisten] MongoDB starting : pid=31 port=27017 dbpath=/opt/bitnami/mongodb/data/db 64-bit host=my-release-mongodb-primary-0
2018-08-30T19:58:40.027+0000 I CONTROL  [initandlisten] db version v4.0.2
2018-08-30T19:58:40.027+0000 I CONTROL  [initandlisten] git version: fc1573ba18aee42f97a3bb13b67af7d837826b47
2018-08-30T19:58:40.027+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.0f  25 May 2017
2018-08-30T19:58:40.027+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2018-08-30T19:58:40.027+0000 I CONTROL  [initandlisten] modules: none
2018-08-30T19:58:40.027+0000 I CONTROL  [initandlisten] build environment:
2018-08-30T19:58:40.027+0000 I CONTROL  [initandlisten]     distmod: debian92
2018-08-30T19:58:40.027+0000 I CONTROL  [initandlisten]     distarch: x86_64
2018-08-30T19:58:40.027+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2018-08-30T19:58:40.027+0000 I CONTROL  [initandlisten] options: { config: "/opt/bitnami/mongodb/conf/mongodb.conf", net: { bindIpAll: true, ipv6: true, port: 27017, unixDomainSocket: { enabled: true, pathPrefix: "/opt/bitnami/mongodb/tmp" } }, processManagement: { fork: false, pidFilePath: "/opt/bitnami/mongodb/tmp/mongodb.pid" }, replication: { replSetName: "rs0" }, security: { authorization: "enabled", keyFile: "/opt/bitnami/mongodb/conf/keyfile" }, setParameter: { enableLocalhostAuthBypass: "true" }, storage: { dbPath: "/opt/bitnami/mongodb/data/db", journal: { enabled: true } }, systemLog: { destination: "file", logAppend: true, path: true } }
2018-08-30T19:58:40.028+0000 I STORAGE  [initandlisten] Detected data files in /opt/bitnami/mongodb/data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2018-08-30T19:58:40.028+0000 I STORAGE  [initandlisten]
2018-08-30T19:58:40.028+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2018-08-30T19:58:40.028+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2018-08-30T19:58:40.028+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3475M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2018-08-30T19:58:40.764+0000 I STORAGE  [initandlisten] WiredTiger message [1535659120:764521][31:0x7f5ae0c989c0], txn-recover: Main recovery loop: starting at 3/26752
2018-08-30T19:58:40.765+0000 I STORAGE  [initandlisten] WiredTiger message [1535659120:765016][31:0x7f5ae0c989c0], txn-recover: Recovering log 3 through 4
2018-08-30T19:58:40.830+0000 I STORAGE  [initandlisten] WiredTiger message [1535659120:830803][31:0x7f5ae0c989c0], txn-recover: Recovering log 4 through 4
2018-08-30T19:58:40.882+0000 I STORAGE  [initandlisten] WiredTiger message [1535659120:882885][31:0x7f5ae0c989c0], txn-recover: Set global recovery timestamp: 5b884c3c00000001
2018-08-30T19:58:40.907+0000 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(1535659068, 1)
2018-08-30T19:58:40.907+0000 I STORAGE  [initandlisten] Triggering the first stable checkpoint. Initial Data: Timestamp(1535659068, 1) PrevStable: Timestamp(0, 0) CurrStable: Timestamp(1535659068, 1)
2018-08-30T19:58:40.925+0000 I STORAGE  [initandlisten] Starting WiredTigerRecordStoreThread local.oplog.rs
2018-08-30T19:58:40.925+0000 I STORAGE  [initandlisten] The size storer reports that the oplog contains 20 records totaling to 2648 bytes
2018-08-30T19:58:40.925+0000 I STORAGE  [initandlisten] Scanning the oplog to determine where to place markers for truncation
2018-08-30T19:58:40.991+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/opt/bitnami/mongodb/data/db/diagnostic.data'
2018-08-30T19:58:41.006+0000 I REPL     [initandlisten] Rollback ID is 1
2018-08-30T19:58:41.008+0000 I REPL     [initandlisten] Recovering from stable timestamp: Timestamp(1535659068, 1) (top of oplog: { ts: Timestamp(1535659068, 1), t: 2 }, appliedThrough: { ts: Timestamp(0, 0), t: -1 }, TruncateAfter: Timestamp(0, 0))
2018-08-30T19:58:41.008+0000 I REPL     [initandlisten] Starting recovery oplog application at the stable timestamp: Timestamp(1535659068, 1)
2018-08-30T19:58:41.008+0000 I REPL     [initandlisten] No oplog entries to apply for recovery. Start point is at the top of the oplog.
2018-08-30T19:58:41.015+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
2018-08-30T19:58:41.018+0000 I CONTROL  [LogicalSessionCacheRefresh] Sessions collection is not set up; waiting until next sessions refresh interval: Replication has not yet been configured
2018-08-30T19:58:41.018+0000 I CONTROL  [LogicalSessionCacheReap] Sessions collection is not set up; waiting until next sessions reap interval: Replication has not yet been configured
2018-08-30T19:58:41.038+0000 W NETWORK  [replexec-0] getaddrinfo("my-release-mongodb-primary-0.my-release-mongodb-headless.default") failed: Name or service not known
2018-08-30T19:58:41.084+0000 W NETWORK  [replexec-0] getaddrinfo("my-release-mongodb-secondary-0.my-release-mongodb-headless.default") failed: Name or service not known
2018-08-30T19:58:41.103+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:33240 #1 (1 connection now open)
2018-08-30T19:58:41.104+0000 I NETWORK  [conn1] received client metadata from 127.0.0.1:33240 conn1: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.0.2" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 9 (stretch)"", architecture: "x86_64", version: "Kernel 4.15.0" } }
2018-08-30T19:58:41.110+0000 I NETWORK  [conn1] end connection 127.0.0.1:33240 (0 connections now open)
2018-08-30T19:58:41.131+0000 W NETWORK  [replexec-0] getaddrinfo("my-release-mongodb-arbiter-0.my-release-mongodb-headless.default") failed: Name or service not known
2018-08-30T19:58:41.157+0000 W REPL     [replexec-0] Locally stored replica set configuration does not have a valid entry for the current node; waiting for reconfig or remote heartbeat; Got "NodeNotFound: No host described in new configuration 3 for replica set rs0 maps to this node" while validating { _id: "rs0", version: 3, protocolVersion: 1, writeConcernMajorityJournalDefault: true, members: [ { _id: 0, host: "my-release-mongodb-primary-0.my-release-mongodb-headless.default:27017", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 5.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 1, host: "my-release-mongodb-secondary-0.my-release-mongodb-headless.default:27017", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 2, host: "my-release-mongodb-arbiter-0.my-release-mongodb-headless.default:27017", arbiterOnly: true, buildIndexes: true, hidden: false, priority: 0.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: -1, catchUpTakeoverDelayMillis: 30000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('5b884bb52c263e0a5dc00ad9') } }
2018-08-30T19:58:41.158+0000 I REPL     [replexec-0] New replica set config in use: { _id: "rs0", version: 3, protocolVersion: 1, writeConcernMajorityJournalDefault: true, members: [ { _id: 0, host: "my-release-mongodb-primary-0.my-release-mongodb-headless.default:27017", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 5.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 1, host: "my-release-mongodb-secondary-0.my-release-mongodb-headless.default:27017", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 2, host: "my-release-mongodb-arbiter-0.my-release-mongodb-headless.default:27017", arbiterOnly: true, buildIndexes: true, hidden: false, priority: 0.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: -1, catchUpTakeoverDelayMillis: 30000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('5b884bb52c263e0a5dc00ad9') } }
2018-08-30T19:58:41.160+0000 I REPL     [replexec-0] This node is not a member of the config
2018-08-30T19:58:41.160+0000 I REPL     [replexec-0] transition to REMOVED from STARTUP
2018-08-30T19:58:41.160+0000 I REPL     [replexec-0] Starting replication storage threads
2018-08-30T19:58:41.162+0000 I REPL     [replexec-0] Starting replication fetcher thread
2018-08-30T19:58:41.163+0000 I REPL     [replexec-0] Starting replication applier thread
2018-08-30T19:58:41.163+0000 I REPL     [replexec-0] Starting replication reporter thread
2018-08-30T19:58:41.165+0000 I REPL     [rsSync-0] Starting oplog application
2018-08-30T19:58:44.132+0000 I NETWORK  [listener] connection accepted from 172.17.0.6:47702 #2 (1 connection now open)
2018-08-30T19:58:44.145+0000 I ACCESS   [conn2] Successfully authenticated as principal __system on local
2018-08-30T19:58:44.146+0000 I NETWORK  [conn2] end connection 172.17.0.6:47702 (0 connections now open)
2018-08-30T19:58:51.090+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:33272 #3 (1 connection now open)
2018-08-30T19:58:51.091+0000 I NETWORK  [conn3] received client metadata from 127.0.0.1:33272 conn3: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.0.2" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 9 (stretch)"", architecture: "x86_64", version: "Kernel 4.15.0" } }
2018-08-30T19:58:51.096+0000 I NETWORK  [conn3] end connection 127.0.0.1:33272 (0 connections now open)
2018-08-30T19:58:58.019+0000 I NETWORK  [listener] connection accepted from 172.17.0.5:41548 #4 (1 connection now open)
2018-08-30T19:58:58.020+0000 I NETWORK  [conn4] end connection 172.17.0.5:41548 (0 connections now open)
2018-08-30T19:58:58.080+0000 I NETWORK  [listener] connection accepted from 172.17.0.5:41550 #5 (1 connection now open)
```

and rs.status() output is

```
MongoDB shell version v4.0.2
connecting to: mongodb://127.0.0.1:27017/admin
MongoDB server version: 4.0.2
{
	"operationTime" : Timestamp(1535659068, 1),
	"ok" : 0,
	"errmsg" : "Our replica set config is invalid or we are not a member of it",
	"code" : 93,
	"codeName" : "InvalidReplicaSetConfig",
	"$clusterTime" : {
		"clusterTime" : Timestamp(1535659068, 1),
		"signature" : {
			"hash" : BinData(0,"jbjhlvwqxQwn7SjRRxwBLKqByCA="),
			"keyId" : NumberLong("6595604916520091649")
		}
	}
}
```

This is the same on primary & secondary nodes.

**Describe the results you expected:**
The replica set gets configured correcty.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**
Chart version - stable/mongodb v4.2.1

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:36:34Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Run on minikube
```
minikube version: v0.28.2
```
PVC
```
NAME                                     STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
datadir-my-release-mongodb-primary-0     Bound     pvc-98c24a2c-ac8e-11e8-9240-08002795cf06   8Gi        RWO            standard       56m
datadir-my-release-mongodb-secondary-0   Bound     pvc-98cd41e2-ac8e-11e8-9240-08002795cf06   8Gi        RWO            standard       56m
```
PV
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                                            STORAGECLASS   REASON    AGE
pvc-98c24a2c-ac8e-11e8-9240-08002795cf06   8Gi        RWO            Delete           Bound     default/datadir-my-release-mongodb-primary-0     standard                 57m
pvc-98cd41e2-ac8e-11e8-9240-08002795cf06   8Gi        RWO            Delete           Bound     default/datadir-my-release-mongodb-secondary-0   standard                 57m
```

**Comment by juan131** [comment]
Hi @euan-tilley 

Thanks for reporting it! I'm able to reproduce the error you described. I'd like @tompizmor to take a look at it since we already have other similar issues with the replica set configuration. 

We'll come back to you with news asap.

**Comment by pete-woods** [comment]
I get the same issue when using docker swarm. When resuming,  the secondaries start spewing this out into the logs:

```
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | 
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | 
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | Welcome to the Bitnami mongodb container
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | Welcome to the Bitnami mongodb container
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | 
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | 
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | nami    INFO  Initializing mongodb
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | nami    INFO  Initializing mongodb
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | mongodb INFO  ==> Deploying MongoDB from scratch...
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | mongodb INFO  ==> No injected configuration files found. Creating default config files...
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | mongodb INFO  ==> Deploying MongoDB from scratch...
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | mongodb INFO  ==> No injected configuration files found. Creating default config files...
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | mongodb INFO  ==> Writing keyfile for replica set authentication
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | mongodb INFO  ==> Writing keyfile for replica set authentication
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | mongodb INFO  ==> Configuring MongoDB replica set
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | mongodb INFO  ==> Configuring MongoDB replica set
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | mongodb INFO  ==> Enabling MongoDB replica set mode
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | mongodb INFO  ==> Enabling MongoDB replica set mode
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | mongodb INFO  ==> Configuring MongoDB secondary node
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | mongodb INFO  Trying to connect to MongoDB server
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | mongodb INFO  Found MongoDB server listening at mongodb-primary:27017
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | mongodb INFO  ==> Configuring MongoDB secondary node
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | mongodb INFO  Cannot connect to MongoDB server. Retrying in 5 seconds...:
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | mongodb INFO  Trying to connect to MongoDB server
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | 2018-09-04T12:32:19.112+0000 E QUERY    [js] Error: not master and slaveOk=false :
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | mongodb INFO  Found MongoDB server listening at mongodb-primary:27017
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | mongodb INFO  Cannot connect to MongoDB server. Retrying in 5 seconds...:
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | _getErrorWithCode@src/mongo/shell/utils.js:25:13
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | DB.prototype.getUsers@src/mongo/shell/db.js:1763:1
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | 2018-09-04T12:32:19.106+0000 E QUERY    [js] Error: not master and slaveOk=false :
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | @(shell eval):1:1
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | _getErrorWithCode@src/mongo/shell/utils.js:25:13
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | 
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | DB.prototype.getUsers@src/mongo/shell/db.js:1763:1
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | 
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | 
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | @(shell eval):1:1
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | 
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | mongodb INFO  Cannot connect to MongoDB server. Retrying in 5 seconds...:
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | 
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | 2018-09-04T12:32:24.198+0000 E QUERY    [js] Error: not master and slaveOk=false :
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | 
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | mongodb INFO  Cannot connect to MongoDB server. Retrying in 5 seconds...:
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | _getErrorWithCode@src/mongo/shell/utils.js:25:13
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | 2018-09-04T12:32:24.195+0000 E QUERY    [js] Error: not master and slaveOk=false :
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | DB.prototype.getUsers@src/mongo/shell/db.js:1763:1
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | @(shell eval):1:1
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | _getErrorWithCode@src/mongo/shell/utils.js:25:13
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | DB.prototype.getUsers@src/mongo/shell/db.js:1763:1
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | 
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | 
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | @(shell eval):1:1
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | 
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | 
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | mongodb INFO  Cannot connect to MongoDB server. Retrying in 5 seconds...:
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | 
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | 2018-09-04T12:32:29.283+0000 E QUERY    [js] Error: not master and slaveOk=false :
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | _getErrorWithCode@src/mongo/shell/utils.js:25:13
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | 
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | DB.prototype.getUsers@src/mongo/shell/db.js:1763:1
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | mongodb INFO  Cannot connect to MongoDB server. Retrying in 5 seconds...:
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | @(shell eval):1:1
stack_mongodb-secondary.2.zj094bau1y3o@linuxkit-025000000001    | 
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | 2018-09-04T12:32:29.283+0000 E QUERY    [js] Error: not master and slaveOk=false :
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | _getErrorWithCode@src/mongo/shell/utils.js:25:13
stack_mongodb-secondary.1.4suigqnvqs34@linuxkit-025000000001    | DB.prototype.getUsers@src/mongo/shell/db.js:1763:1
```

**Comment by pete-woods** [comment]
I discovered the problem with my deployment was trying to use Docker swarm's replicas (combined with bypassing the router mesh by making the replicated services use `dnsrr` endpoints).

A working configuration is as follows:
```
version: '3.6'

x-config:
  - &mongodb-password 'mongopass123'
  - &mongodb-root-password 'mongoroot123'
  - &mongodb-replica-set-key 'replicakey123'

x-mongodb-base: &mongodb-base
  image: 'bitnami/mongodb:4.0'

x-mongodb-base-environment: &mongodb-base-environment
  MONGODB_REPLICA_SET_KEY: *mongodb-replica-set-key
  MONGODB_ADVERTISED_HOSTNAME: '{{.Service.Name}}'

x-mongodb-secondary-environment: &mongodb-secondary-environment
  MONGODB_PRIMARY_ROOT_PASSWORD: *mongodb-root-password
  MONGODB_PRIMARY_HOST: 'mongodb-primary'
  MONGODB_REPLICA_SET_MODE: 'secondary'

volumes:
  mongodb_master_data:
    driver: local

services:

  mongodb-primary:
    <<: *mongodb-base
    environment:
      <<: *mongodb-base-environment
      MONGODB_DATABASE: 'database'
      MONGODB_USERNAME: 'user'
      MONGODB_PASSWORD: *mongodb-password
      MONGODB_ROOT_PASSWORD: *mongodb-root-password
      MONGODB_REPLICA_SET_MODE: 'primary'
    volumes:
      - 'mongodb_master_data:/bitnami'

  mongodb-secondary-1:
    <<: *mongodb-base
    environment:
      <<: *mongodb-base-environment
      <<: *mongodb-secondary-environment

  mongodb-secondary-2:
    <<: *mongodb-base
    environment:
      <<: *mongodb-base-environment
      <<: *mongodb-secondary-environment
```

**Comment by tompizmor** [comment]
@pete-woods I am glad you find a solution for your docker-swarm scenario.

@euan-tilley There is a new version of the chart that should fix this issue. The PR https://github.com/helm/charts/pull/7546 has just been merged. 
With this new chart I am not able to reproduce the issue anymore.

**Comment by euan-tilley** [comment]
Yep this has fixed the issue I was having. However some people who don't use the default 'svc.cluster.local' domain name may still have issues!

**Comment by tompizmor** [comment]
You are right. I guess an option is to make the cluster domain configurable so it defaults to `cluster.local` but it can be changed while installing the chart. Do you agree?

**Comment by euan-tilley** [comment]
That would work

**Comment by tompizmor** [comment]
@euan-tilley PR sent and merged https://github.com/helm/charts/pull/7655.
I am going to close this issue. Please feel free to re-open or open a new one if you find any other issue.
