### ISSUE TITLE
[stable/mongodb] MongoDB custom configmap settings not working for replicaset

### ISSUE THREAD

**Issue by kwill4026** [bitnami/bitnami-docker-mongodb#171]
**Describe the bug**:

I was able to set up TLS/SSL into the mongodb helm chart for secure communication between the mongod's and its servers by using self signed certs. I have a init script located in files/docker-entrypoint-initdb.d/ which creates the root CA that gets created in the master pod as well as the in the secondaries using the same CA. The second part of the script will then use that CA to generate server certs which will be unique for each pod that gets created. 
The next step is to enable to the mongod server to accept TLS settings via the configmap settings which in this case will be adding net.ssl.CAFile and net.ssl.PEMKeyfile. However when attempting to add this in the values.yaml file, the pod is unable to run and immediately enters a Error state.

**Version of Helm and Kubernetes**:
```
Helm Version:
 Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

Kubernetes: 
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-29T16:15:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-2e569f", GitCommit:"2e569fd887357952e506846ed47fc30cc385409a", GitTreeState:"clean", BuildDate:"2019-07-25T23:13:33Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: 
```
stable/mongodb
```

**What happened**:
Running the default mongodb helm cart as a standalone (replicaSet.enabled=false) without modifying the configmap settings in the values.yaml file causes the pod to run fine with no issues and also allows me to connect to the mongo as the root user. 
```
NAME                                READY   STATUS    RESTARTS   AGE
pod/test-mongodb-585f9c459f-vcvpb   1/1     Running   0          70s
```
```
I have no name!@test-mongodb-585f9c459f-vcvpb:/$ mongo admin -u root -p $MONGODB_ROOT_PASSWORD 
MongoDB shell version v4.0.12
connecting to: mongodb://127.0.0.1:27017/admin?gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("58624231-2786-4204-a11f-ad858bab62fb") }
MongoDB server version: 4.0.12

```

However using the same mongod conf settings in that previous working image to manually input into the configmap section of the values.yaml file utilizing the same standalone settings causes the image to recognize a custom mongodb.conf has been detected. And is able to complete the MongoDB setup however it restarts the server once and when attempting to connect to the mongo as a root user it fails. 

```
NAME                                READY   STATUS    RESTARTS   AGE
pod/test-mongodb-7f54c46c74-4fgx2   1/1     Running   1          93s
```
```
I have no name!@test-mongodb-7f54c46c74-4fgx2:/$ mongo admin -u root -p $MONGODB_ROOT_PASSWORD
MongoDB shell version v4.0.12
connecting to: mongodb://127.0.0.1:27017/admin?gssapiServiceName=mongodb
2019-09-10T15:26:36.182+0000 E QUERY    [js] Error: Authentication failed. :
connect@src/mongo/shell/mongo.js:344:17
@(connect):2:6
exception: connect failed
I have no name!@test-mongodb-7f54c46c74-4fgx2:/$ 

```
This is the configmap I am using. Which is the exact same one as when I am running the mongodb chart with its default settings and I bash into the pod to view the mongodb.conf file.
```
configmap: 
   storage:
      dbPath: /bitnami/mongodb/data/db
      journal:
          enabled: true
      directoryPerDB: false
      systemLog:
          destination: file
          quiet: false
          logAppend: true
          logRotate: reopen
          path: /opt/bitnami/mongodb/logs/mongodb.log
          verbosity: 0
      net:
          port: 27017
          unixDomainSocket:
              enabled: true
              pathPrefix: /opt/bitnami/mongodb/tmp
          bindIpAll: true
      security: 
          authorized: enabled 
```

Now this time I enabled the replicaSet and run the same configuration type with me manually specifying the configmap settings in the values.yaml file. The pods this time instead of running at least, immediately crashes and doesnt complete the setup once it detects there is a custom mongod.conf file 
```
user@ip-10-114-23-236 mongodb]$ kubectl get all
NAME                           READY   STATUS             RESTARTS   AGE
pod/test-mongodb-arbiter-0     0/1     CrashLoopBackOff   4          2m2s
pod/test-mongodb-primary-0     0/1     CrashLoopBackOff   3          2m2s
pod/test-mongodb-secondary-0   0/1     Error              4          2m2s

[user@ip-10-114-23-236 mongodb]$ kubectl logs pod/test-mongodb-primary-0
 16:58:24.32 
 16:58:24.32 Welcome to the Bitnami mongodb container
 16:58:24.32 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
 16:58:24.33 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
 16:58:24.33 Send us your feedback at containers@bitnami.com
 16:58:24.33 
 16:58:24.33 INFO  ==> ** Starting MongoDB setup **
 16:58:24.34 INFO  ==> Validating settings in MONGODB_* env vars...
 16:58:24.34 INFO  ==> Initializing MongoDB...
 16:58:24.35 INFO  ==> Deploying MongoDB from scratch...
 16:58:24.35 INFO  ==> Custom configuration /opt/bitnami/mongodb/conf/mongodb.conf detected!
```

**What you expected to happen**:
I expect to be able to specify custom configmap settings via the configmap section in the values.yaml file regardless if its a standalone or replicaset. Once the custom configmap is specified, I expect to be able to run the pods and be able to connect to the mongo.
I expect whatever settings I specify in the configmap section to create the pod thus I will be able to specify TLS/SSL settings in the configmap section to include
the net.ssl.CAFile and net.ssl.PEMKeyFile such as this: 
```
net:
          port: 27017
          ssl: 
             CAFile: /pathICreated/mongodb-ca.crt
             PEMKeyFile: /pathICreated/mongodb.pem
             mode: preferSSL
          unixDomainSocket:
              enabled: true
              pathPrefix: /opt/bitnami/mongodb/tmp
          bindIpAll: true
```
Alternatively the values.yaml file specifies a configmap section mongo conf settings as well as mongod and mongos Command-Line Options using the extra flags settings. Therefore when I attempt to specify TLS/SSL settings via the MongoDB additional command line flags in the values.yaml file, I expect it to take in those settings. However for some reason, in the values.yaml file when I have the configmap section set back to the default (configmap: []) and decide to specify parameters in the extra flags section, it is able to take parameters like "--wiredTigerCacheSizeGB=2" and "--port=27017" but once I specify other settings, especially TLS/SSL settings, it doesnt run the pod. I expect to be able to specify the following in the values.yaml file which will cause the mongod server to start up with TLS/SSL and then allow a client to connect to it since its TLS/SSL enabled. 
```
mongodbExtraFlags:
      - "--sslMode=preferSSL"
      - "--sslPEMKeyFile=/pathICreated/mongodb.pem"
      - "--sslCAFile=/pathICreated/mongodb-ca.crt"
mongodbClientExtraFlags: 
      - "--ssl"
      - "--sslPEMKeyFile=/pathICreated/mongodb.pem"
      - "--sslCAFile=/pathICreated/mongodb-ca.crt"
```

**How to reproduce it** (as minimally and precisely as possible):
Run the stable/mongodb chart with no changes to the configmap section as a standalone then attempt to do the same as a standalone but include your own configmap. 
Also do the same exact thing with the chart as a replicaset. 

When attempting to use command line options by utilizing the MONGODB_EXTRA_FLAGS and MONGODB_CLIENT_EXTRA_FLAGS section, include TLS/SSL mongo settings and watch the pods not load up because of this. 

**Anything else we need to know**:
As I stated I was able to create a root CA and the server certs for each pod but I am unable to start the mongo to create the replicaset to be TLS/SSL enabled. 
According to the bitnami/bitnami-docker-mongodb located here 
```
https://github.com/bitnami/bitnami-docker-mongodb
``` 
This container supports enabling SSL/TLS between nodes in the cluster, as well as between mongo clients and nodes, by setting the MONGODB_EXTRA_FLAGS and MONGODB_CLIENT_EXTRA_FLAGS environment variables or by specifying it in the mongo configmap settings.

**Comment by miguelaeh** [comment]
Hi @kwill4026 ,
Could you try to modify the `configmap.yml` file locally and write your configuration file directly?
I mean:
confimap.yml
```diff
{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "mongodb.fullname" . }}
data:
  mongodb.conf: |-
- {{ toYaml .Values.configmap | indent 4 }} 
+    #your configration file
{{- end }}
```

**Comment by kwill4026** [comment]
@miguelaeh Hello so I tried this setup and still the pods were not able to run. First I had to remove the references to **{{- if .Values.configmap }}** in the **statefulset-arbiter-rs.yaml, statefulset-primary-rs.yaml, statefulset-secondary-rs.yaml, and configmap.yaml** files since I am writing the mongodb config file directly in the configmap.yaml file and am NOT referencing any values from the **configmap**: section in the values.yaml file.  If I did not do this and simply just removed the **{{ toYaml .Values.configmap | indent 4 }} **  portion and included my config file, it would have not taken this config file and instead just ran the default mongodb config paramaters as if I specified the values.yaml file to have no configmap values. This is because the configmap.yaml file is looking to see if  **{{- if .Values.configmap }}** is true and has parameters listed. 
As a result my configmap.yaml file looks like this: 
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "mongodb.fullname" . }}
data:
  mongodb.conf: |-
    storage:
      dbPath: /bitnami/mongodb/data/db
      journal:
        enabled: true
    systemLog:
      destination: file
      logAppend: true
      path: /opt/bitnami/mongodb/logs/mongodb.log
    net:
      port: 27017
      bindIp: 0.0.0.0
      unixDomainSocket:
        enabled: true
        pathPrefix: /opt/bitnami/mongodb/tmp
    replication:
      replSetName: rs0
    processManagement:
       fork: false
       pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
    setParameter:
       enableLocalhostAuthBypass: true
    security:
      authorization: enabled
      keyFile: /opt/bitnami/mongodb/conf/keyfile
```

```
NAME                           READY   STATUS             RESTARTS   AGE
pod/test-mongodb-arbiter-0     0/1     CrashLoopBackOff   2          33s
pod/test-mongodb-primary-0     0/1     Error              1          33s
pod/test-mongodb-secondary-0   0/1     Error              1          33s
```
The log file for the pods looks as follows which shows its recognizes the configmap because a new mongodb.conf file has been detected, but it will not continue the MongoDB creation setup from there. 
```
$ kubectl logs pod/test-mongodb-primary-0
 13:54:51.14 
 13:54:51.15 Welcome to the Bitnami mongodb container
 13:54:51.15 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
 13:54:51.15 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
 13:54:51.15 Send us your feedback at containers@bitnami.com
 13:54:51.15 
 13:54:51.16 INFO  ==> ** Starting MongoDB setup **
 13:54:51.17 INFO  ==> Validating settings in MONGODB_* env vars...
 13:54:51.17 INFO  ==> Initializing MongoDB...
 13:54:51.17 INFO  ==> Deploying MongoDB from scratch...
 13:54:51.18 INFO  ==> Custom configuration /opt/bitnami/mongodb/conf/mongodb.conf detected!
```

**Comment by miguelaeh** [comment]
Hi @kwill4026 ,
I can reproduce it, with your configuration file, but using the default one it works so it could be a problem of your configuration file. This is the default one:
```
    # mongod.conf
    # for documentation of all options, see:
    #   http://docs.mongodb.org/manual/reference/configuration-options/

    # where and how to store data.
    storage:
      dbPath: /bitnami/mongodb/data/db
      journal:
        enabled: true
      directoryPerDB: false

    # where to write logging data.
    systemLog:
      destination: file
      quiet: false
      logAppend: true
      logRotate: reopen
      path: /opt/bitnami/mongodb/logs/mongodb.log
      verbosity: 0

    # network interfaces
    net:
      port: 27017
      unixDomainSocket:
        enabled: true
        pathPrefix: /opt/bitnami/mongodb/tmp
      ipv6: false
      bindIpAll: true

    # replica set options
    #replication:
      #replSetName: replicaset
      #enableMajorityReadConcern: true

    # process management options
    processManagement:
       fork: false
       pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid

    # set parameter options
    setParameter:
       enableLocalhostAuthBypass: true

    # security options
    security:
      authorization: disabled
      #keyFile: replace_me
```
Could you try with it?

**Comment by ear-dev** [comment]
I am having the same issue.  However, when I used the default config file in the `configmap` verbatim (i.e. kept the keyFile and replicaSet option commented out) then I got much further:

```
INFO  ==> ** Starting MongoDB setup **
INFO  ==> Validating settings in MONGODB_* env vars...
INFO  ==> Initializing MongoDB...
INFO  ==> Deploying MongoDB from scratch...
INFO  ==> Custom configuration /opt/bitnami/mongodb/conf/mongodb.conf detected!
INFO  ==> Creating users...
INFO  ==> Users created
INFO  ==> Writing keyfile for replica set authentication: BC3KBUuWmI /opt/bitnami/mongodb/conf/keyfile
WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
INFO  ==> Configuring MongoDB replica set...
WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
INFO  ==> Stopping MongoDB...
INFO  ==> Trying to connect to MongoDB server...
INFO  ==> Found MongoDB server listening at widechat-mongodb-test:27017 !
INFO  ==> MongoDB server listening and working at widechat-mongodb-test:27017 !
INFO  ==> Primary node ready.
INFO  ==> Adding node to the cluster
INFO  ==> Configuring MongoDB arbiter node
INFO  ==> Stopping MongoDB...
```
The issue seems to be here?
https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.0/debian-9/rootfs/libmongodb.sh#L381

**Comment by miguelaeh** [comment]
Hi @ear-dev ,
The problem here is that a ConfigMap is not writable once it is mounted. So that `if` statement is there to prevent a write permissions error.
To set in the configuration file the keys that in `libmongodb.sh` are preceded by the `mongodb_config_apply_regex` function you need to write them on the configMap manually and mount it.
If you are going to use a custom configuration file, I would ensure that all the parameters are set to the value you want.
Basically, that log is not an error just an info that some parameters such as `$MONGODB_REPLICA_SET_NAME` will not be set in the configMap using the env var, just add it to the configuration file in the configMap manually.

**Comment by ear-dev** [comment]
Thanks Miguelaeh.... that is the way I understood how it worked, but the problem I'm having is that when I do fill out the configMap manually, with all the values, then I also get that crash just after `Custom configuration /opt/bitnami/mongodb/conf/mongodb.conf detected!`.  So far I have not been able to figure out what the issue is that is causing the crash. For some reason, not filling out key file location in my configMap seemed to avoid the crash and got the process much further along.....

**Comment by kwill4026** [comment]
Hello @miguelaeh so I was able to get the configmap to take for the standalone, just as you did by specifying it in the configmap.yaml file as follows.
```
{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "mongodb.fullname" . }}
data:
  mongodb.conf: |-
    # mongod.conf
    # for documentation of all options, see:
    #   http://docs.mongodb.org/manual/reference/configuration-options/

    # where and how to store data.
    storage:
      dbPath: /bitnami/mongodb/data/db
      journal:
        enabled: true
      directoryPerDB: false

    # where to write logging data.
    systemLog:
      destination: file
      quiet: false
      logAppend: true
      logRotate: reopen
      path: /opt/bitnami/mongodb/logs/mongodb.log
      verbosity: 0

    # network interfaces
    net:
      port: 27017
      unixDomainSocket:
        enabled: true
        pathPrefix: /opt/bitnami/mongodb/tmp
      ipv6: false
      bindIpAll: true

    # replica set options
    #replication:
      #replSetName: replicaset
      #enableMajorityReadConcern: true

    # process management options
    processManagement:
       fork: false
       pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid

    # set parameter options
    setParameter:
       enableLocalhostAuthBypass: true

    # security options
    security:
      authorization: disabled
      #keyFile: replace_me
{{- end }}
```
Alternatively, I was also able to specify the same default config settings in the values.yaml **configmap**: section and watch the pod take in the settings and start the pod as a standalone. 
```
# Entries for the MongoDB config file
configmap:
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false

    # where to write logging data.
  systemLog:
    destination: file
    quiet: false
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0

    # network interfaces
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    ipv6: false
    bindIp: 0.0.0.0

  # replica set options
  #replication:
     #replSetName: replicaset
     #enableMajorityReadConcern: true

  # process management options
  processManagement:
     fork: false
     pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid

    # set parameter options
  setParameter:
     enableLocalhostAuthBypass: true

    # security options
  security:
    authorization: disabled
    #keyFile: replace_me
```

Both ways show the standalone pod's logs to look as the following. In which it causes the pods to run as intended with the custom mongo conf settings and does not cause a restart of the container.  
```
12:01:29.71 INFO  ==> ** Starting MongoDB setup **
 12:01:29.72 INFO  ==> Validating settings in MONGODB_* env vars...
 12:01:29.73 INFO  ==> Initializing MongoDB...
 12:01:29.73 INFO  ==> Deploying MongoDB from scratch...
 12:01:29.73 INFO  ==> Custom configuration /opt/bitnami/mongodb/conf/mongodb.conf detected!
 12:01:30.41 INFO  ==> Creating users...
 12:01:30.41 INFO  ==> Creating root user...
 12:01:30.61 INFO  ==> Enabling authentication...
 12:01:30.61 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 12:01:30.61 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 12:01:30.61 INFO  ==> Users created
 12:01:30.62 INFO  ==> Stopping MongoDB...
 12:01:31.62 INFO  ==> 
 12:01:31.62 INFO  ==> ########################################################################
 12:01:31.62 INFO  ==>  Installation parameters for MongoDB:
 12:01:31.62 INFO  ==> (Passwords are not shown for security reasons)
 12:01:31.63 INFO  ==> ########################################################################
 12:01:31.63 INFO  ==> 
 12:01:31.63 INFO  ==> Loading custom scripts...
find: '/docker-entrypoint-initdb.d/': No such file or directory
 12:01:31.63 INFO  ==> ** MongoDB setup finished! **

 12:01:31.64 INFO  ==> ** Starting MongoDB **
2019-09-18T12:01:31.676+0000 I STORAGE  [main] Max cache overflow file size custom option: 0
2019-09-18T12:01:31.676+0000 I CONTROL  [main] ***** SERVER RESTARTED *****
2019-09-18T12:01:31.678+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2019-09-18T12:01:31.681+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/bitnami/mongodb/data/db 64-bit host=test-mongodb-c95f8bb8c-vcc7f
2019-09-18T12:01:31.681+0000 I CONTROL  [initandlisten] db version v4.0.12
2019-09-18T12:01:31.681+0000 I CONTROL  [initandlisten] git version: 5776e3cbf9e7afe86e6b29e22520ffb6766e95d4
2019-09-18T12:01:31.681+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.0k  28 May 2019
2019-09-18T12:01:31.681+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2019-09-18T12:01:31.681+0000 I CONTROL  [initandlisten] modules: none
2019-09-18T12:01:31.681+0000 I CONTROL  [initandlisten] build environment:
2019-09-18T12:01:31.681+0000 I CONTROL  [initandlisten]     distmod: debian92
2019-09-18T12:01:31.681+0000 I CONTROL  [initandlisten]     distarch: x86_64
2019-09-18T12:01:31.681+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2019-09-18T12:01:31.681+0000 I CONTROL  [initandlisten] options: { config: "/opt/bitnami/mongodb/conf/mongodb.conf", net: { bindIp: "0.0.0.0", ipv6: false, port: 27017, unixDomainSocket: { enabled: true, pathPrefix: "/opt/bitnami/mongodb/tmp" } }, processManagement: { fork: false, pidFilePath: "/opt/bitnami/mongodb/tmp/mongodb.pid" }, security: { authorization: "disabled" }, setParameter: { enableLocalhostAuthBypass: "true" }, storage: { dbPath: "/bitnami/mongodb/data/db", directoryPerDB: false, journal: { enabled: true } }, systemLog: { destination: "file", logAppend: true, logRotate: "reopen", path: "/opt/bitnami/mongodb/logs/mongodb.log", quiet: false, verbosity: 0 } }
```
So far this is all good. However I noticed as a standalone when I set **security.authorization** from disabled to enabled in my custom configmap settings and specify in my values.yaml file for 
mongodbRootPassword, mongodbUsername, mongodbPassword, and mongodbDatabase, it causes the pod to start in a Running state with a restart status of 1. I can bash into this standalone pod but cannot log into any mongodb database as the root user or the first general user I specified using the 
mongodbUsername, mongodbPassword, and mongodbDatabase values. 
Why is this?


Where as if I run the stable/mongodb image straight from the helm charts as a standalone without any changes (no custom mongo conf settings) to anything except specifying the mongodbRootPassword, mongodbUsername mongodbPassword, and mongodbDatabase, it allows the pod to run fine. When I bash into the container I can now see in the conf file that security.authorization has been enabled and I can login to the database as a root user and can also log into the specific database I set in the mongodbUsername and mongodDatabase. 
```
# security options
security:
  authorization: enabled
  #keyFile: replace_me
``

```
kubectl exec -it test-mongodb-8cf9d9795-n7dxj bash
I have no name!@test-mongodb-8cf9d9795-n7dxj:/$ mongo -u $MONGODB_USERNAME -p $MONGODB_PASSWORD --authenticationDatabase $MONGODB_DATABASE
MongoDB shell version v4.0.12
connecting to: mongodb://127.0.0.1:27017/?authSource=data&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("4884b2ab-3d0d-47e8-8126-0ed9e600fa68") }
MongoDB server version: 4.0.12
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
	http://docs.mongodb.org/
Questions? Try the support group
	http://groups.google.com/group/mongodb-user
2019-09-18T14:03:13.396+0000 I STORAGE  [main] In File::open(), ::open for '//.mongorc.js' failed with Permission denied
> show dbs
data  0.000GB
> use data
switched to db data
> show collections
friendss
```

**Comment by miguelaeh** [comment]
Hi, 
We replicated and this is a bug, thank you very for reporting, let us investigate it and we will update this thread when we have news.

**Comment by kwill4026** [comment]
Sounds great thanks for looking into it further @miguelaeh

**Comment by miguelaeh** [comment]
Hi @kwill4026 @ear-dev ,
Thank you very much for reporting the issue.
That PR should solve the problem.
Let us know if you have more issues with this.

**Comment by kwill4026** [comment]
Thanks @miguelaeh. How long will it take for the PR be incorporated into the stable/mongodb helm chart if you don't mind me asking.

**Comment by kwill4026** [comment]
@miguelaeh If so I just tried it on the tag of "latest" as well as the tag "4.0.12-debian-9-r49" and still the same error and restart of the pod.

**Comment by miguelaeh** [comment]
Hi @kwill4026 ,
I just tested again whit the image tag `4.0.12-debian-9-r49` and it works now, did you update your repositories? How are you deploying it?
If you have a clone of the GitHub repository just uncomment the lines like this:
```
## Entries for the MongoDB config file. For documentation of all options, see:
##   http://docs.mongodb.org/manual/reference/configuration-options/
##
configmap:
  # where and how to store data.
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false
  # where to write logging data.
  systemLog:
    destination: file
    quiet: false
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0
  # network interfaces
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    ipv6: false
    bindIpAll: true
  # replica set options
  #replication:
    #replSetName: replicaset
    #enableMajorityReadConcern: true
  # process management options
  processManagement:
     fork: false
     pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
  # set parameter options
  setParameter:
     enableLocalhostAuthBypass: true
  # security options
  security:
    authorization: disabled
    #keyFile: /opt/bitnami/mongodb/conf/keyfile
```
And you will see the pods running:
```
mongodb-79d4bbc685-xskp7   1/1     Running   0          37s
```

**Comment by kwill4026** [comment]
@miguelaeh I dont think we are on the same page. I can get this to work with no problem. I'm talking about changing the security.authorization from disabled as you have it currently to **enabled**.
That is what I am attempting to do but the pod restarts, gets in a running state, and when I attempt to bash into the container to login, I am unable to as a admin user with creds or even simply with no creds. 
The way you have it with authorization disabled, lets anyone log in. But I assumed setting it to **enabled** should prevent this and instead require me to login with the admin creds:
 **mongo -u root -p myAdminPassword** yet this does not work.

**Comment by kwill4026** [comment]
@miguelaeh 
```
## Entries for the MongoDB config file. For documentation of all options, see:
##   http://docs.mongodb.org/manual/reference/configuration-options/
##
configmap:
  # where and how to store data.
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false
  # where to write logging data.
  systemLog:
    destination: file
    quiet: false
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0
  # network interfaces
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    ipv6: false
    bindIpAll: true
  # replica set options
  #replication:
    #replSetName: replicaset
    #enableMajorityReadConcern: true
  # process management options
  processManagement:
     fork: false
     pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
  # set parameter options
  setParameter:
     enableLocalhostAuthBypass: true
  # security options
  security:
     authorization: enabled
    #keyFile: /opt/bitnami/mongodb/conf/keyfile
```
I am changing  **authorization: enabled**

**Comment by miguelaeh** [comment]
Hi @kwill4026 ,
Okay, we was talking about two different issues, the PR fixes the ConfigMap error, that was making MongoDB to store data into the wrong directory.
Lets talk now about the authentication error.
`authorization.enabled` will allow MongoDB to use the RBAC authentication, so you need to have the users with the correct roles assigned. Could you check if your admin user has the `userAdminAnyDatabase` role assigned?

**Comment by kwill4026** [comment]
@miguelaeh  lol yea we definitely were. 
So looking at the default bitnami configuration files I see in the code the admin user named "root" has the "root" role
```
mongodb_create_users() {
    local result

    info "Creating users..."
    if [[ -n "$MONGODB_ROOT_PASSWORD" ]] && ! [[ "$MONGODB_REPLICA_SET_MODE"  =~ ^(secondary|arbiter) ]]; then
        info "Creating root user..."
        result=$(mongodb_execute <<EOF
db.getSiblingDB('admin').createUser({ user: 'root', pwd: '$MONGODB_ROOT_PASSWORD', roles: [{role: 'root', db: 'admin'}] })
EOF
)
```

If I pull down the default chart and in the values.yml file specify the admin password and the mongodb user, password, and database, then run the default settings with replicaSet set to true. It looks like it automatically changes the authorization from disabled to enabled which makes sense. But manually changing the custom configmap in the values.yaml file from disabled to enabled doesnt seem to like that.

**Comment by miguelaeh** [comment]
Hi @kwill4026 ,
If you use the configuration file you are responsible to configure all the necessary parameters. As you can see in the `libmongodb.sh` file:
```
    if [[ -n "$MONGODB_ROOT_PASSWORD" ]] || [[ -n "$MONGODB_PASSWORD" ]]; then
        authorization="$(yq read "$MONGODB_CONFIG_FILE" security.authorization)"
        if [[ "$authorization" = "disabled" ]]; then

            info "Enabling authentication..."
            # TODO: replace 'sed' calls with 'yq' once 'yq write' does not remove comments
            mongodb_config_apply_regex "#?authorization:.*" "authorization: enabled"
            mongodb_config_apply_regex "#?enableLocalhostAuthBypass:.*" "enableLocalhostAuthBypass: false"
        fi
    fi
```

The automatic authentication configuration is in case you set the `MONGO_DB_ROOT_PASSWORD` or the `MONGODB_PASSWORD` env. variable, both come from parameters in the `values.yaml`.
As you can see, it sets in the configuration file `authorization: enabled` and `enableLocalhostAuthBypass: false`, that will be not set if you use the configmap, because the env. variables will not be set. The configmap will be the exact configuration file for MongoDB

**Comment by kwill4026** [comment]
So how can I get it that by specifying all the parameters in the configmap section (from the values.yaml), it will cause **authorization: enabled**, **enableLocalhostAuthBypass: false** and allow me to login via the root users password? If the configmap will be the exact configuration file for MongoDB then how come when I specify my config file as follows, my pods do not run.
```
# Entries for the MongoDB config file. For documentation of all options, see:
##   http://docs.mongodb.org/manual/reference/configuration-options/
##
configmap:
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false
  systemLog:
    destination: file
    quiet: false
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    ipv6: false
    bindIpAll: true
  replication:
    replSetName: rs0
    enableMajorityReadConcern: true
  processManagement:
     fork: false
     pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
  setParameter:
     enableLocalhostAuthBypass: false
  security:
    authorization: enabled
    keyFile: /opt/bitnami/mongodb/conf/keyfile
```

Since the config settings take precedence, I would assume me setting all these settings through the configmap will cause the pod to run.

**Comment by miguelaeh** [comment]
Hi @kwill4026 ,
That is because of the `keyfile`, I think there is a bug there too. Please comment that line in the configMap and use and existing secret instead.

**Comment by miguelaeh** [comment]
Hi again @kwill4026 ,
About the `keyfile` there is a template in the `_helpers.tpl` that uses it, but that template is never used and there is not any resource with the name `{{- template "mongodb.fullname" . -}}-keyfile` so the problem is that the key file will not exists and it fails if you set it in the configuration.
I will create another internal task to fix that. Thank you for reporting.

**Comment by kwill4026** [comment]
@miguelaeh I tried comenting out the keyfile line in the configmap. And also uncommented **exisitingSecret** in the values.yaml file to place it with a secret name containing these values: 
```
[xxxx]$ kubectl get secrets mongosecrets -o yaml
apiVersion: v1
data:
  mongodb-password: ZnJhbms=
  mongodb-replica-set-key: MWYyZDFlMmU2N2Rm
  mongodb-root-password: YWRtaW4=
  mongodbDatabase: dGV4dA==
  mongodbUsername: ZnJlZA==
kind: Secret
metadata:
  creationTimestamp: "2019-10-01T17:15:54Z"
  name: mongosecrets
  namespace: default
  resourceVersion: "1727119"
  selfLink: /api/v1/namespaces/default/secrets/mongosecrets
  uid: 202afb6a-e46f-11e9-ab3d-0a40a152b37a
type: Opaque
```
```
## Enable authentication
## ref: https://docs.mongodb.com/manual/tutorial/enable-authentication/
#
usePassword: true
existingSecret: mongosecrets
```

```
NAME                           READY   STATUS             RESTARTS   AGE
pod/test-mongodb-arbiter-0     0/1     CrashLoopBackOff   2          7m20s
pod/test-mongodb-primary-0     1/1     Running            1          7m20s
pod/test-mongodb-secondary-0   1/1     Running            1          7m20s
```

**Comment by miguelaeh** [comment]
Could you provide the logs of the arbiter?

**Comment by kwill4026** [comment]
Here is me running the same again with exisiting secrets.
Starts off:
```
[X.X.X.X@ip-10-114-18-150 mongodb]$ kubectl get all
NAME                                     READY   STATUS    RESTARTS   AGE
pod/cranky-catfish-mongodb-arbiter-0     1/1     Running   0          43s
pod/cranky-catfish-mongodb-primary-0     0/1     Running   1          43s
pod/cranky-catfish-mongodb-secondary-0   1/1     Running   0          43s
```

Arbiter Logs a couple of mins later:
```
[X.X.X.X@ip-10-114-18-150 mongodb]$ kubectl logs pod/cranky-catfish-mongodb-arbiter-0
 12:17:52.58 
 12:17:52.58 Welcome to the Bitnami mongodb container
 12:17:52.58 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
 12:17:52.58 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
 12:17:52.58 Send us your feedback at containers@bitnami.com
 12:17:52.59 
 12:17:52.59 INFO  ==> ** Starting MongoDB setup **
 12:17:52.60 INFO  ==> Validating settings in MONGODB_* env vars...
 12:17:52.60 INFO  ==> Initializing MongoDB...
 12:17:52.60 INFO  ==> Deploying MongoDB from scratch...
 12:17:52.60 INFO  ==> Custom configuration /opt/bitnami/mongodb/conf/mongodb.conf detected!
 12:17:53.30 INFO  ==> Creating users...
 12:17:53.30 INFO  ==> Users created
 12:17:53.30 INFO  ==> Writing keyfile for replica set authentication: 1f2d1e2e67df /opt/bitnami/mongodb/conf/keyfile
 12:17:53.30 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 12:17:53.30 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 12:17:53.30 INFO  ==> Configuring MongoDB replica set...
 12:17:53.30 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 12:17:53.31 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 12:17:53.31 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 12:17:53.31 INFO  ==> Stopping MongoDB...
 12:17:55.29 INFO  ==> Trying to connect to MongoDB server...
 12:17:55.34 INFO  ==> Found MongoDB server listening at cranky-catfish-mongodb:27017 !
exception: connect failed
exception: connect failed
exception: connect failed
exception: connect failed
exception: connect failed
exception: connect failed
exception: connect failed
```

Overall pods status few mins later shows the arbiter be in a **CrashLoopBackOff** state then few seconds later the arbiter is then in a **Running** state with a restart number of 2.  The primary and secondary still has a restart value of 1 whereas the arbiter keeps restarting every few mins. 

Primary Pod logs: 
```
[X.X.X.X@ip-10-114-18-150 mongodb]$ kubectl logs pod/cranky-catfish-mongodb-primary-0
 12:16:21.78 
 12:16:21.78 Welcome to the Bitnami mongodb container
 12:16:21.78 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
 12:16:21.78 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
 12:16:21.78 Send us your feedback at containers@bitnami.com
 12:16:21.78 
 12:16:21.79 INFO  ==> ** Starting MongoDB setup **
 12:16:21.80 INFO  ==> Validating settings in MONGODB_* env vars...
 12:16:21.80 INFO  ==> Initializing MongoDB...
 12:16:21.80 INFO  ==> Deploying MongoDB with persisted data...
 12:16:21.80 INFO  ==> Custom configuration /opt/bitnami/mongodb/conf/mongodb.conf detected!
 12:16:21.80 INFO  ==> Writing keyfile for replica set authentication: 1f2d1e2e67df /opt/bitnami/mongodb/conf/keyfile
 12:16:21.81 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 12:16:21.81 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 12:16:21.81 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 12:16:21.81 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 12:16:21.81 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 12:16:21.81 INFO  ==> 
 12:16:21.81 INFO  ==> ########################################################################
 12:16:21.82 INFO  ==>  Installation parameters for MongoDB:
 12:16:21.82 INFO  ==>    Persisted data and properties have been restored.
 12:16:21.82 INFO  ==>    Any input specified will not take effect.
 12:16:21.82 INFO  ==> (Passwords are not shown for security reasons)
 12:16:21.82 INFO  ==> ########################################################################
 12:16:21.82 INFO  ==> 
 12:16:21.82 INFO  ==> Loading custom scripts...
find: '/docker-entrypoint-initdb.d/': No such file or directory
 12:16:21.82 INFO  ==> ** MongoDB setup finished! **

 12:16:21.83 INFO  ==> ** Starting MongoDB **
2019-10-02T12:16:21.850+0000 I STORAGE  [main] Max cache overflow file size custom option: 0
                               .
                               . 
                               .
2019-10-02T12:16:22.778+0000 I REPL     [initandlisten] Did not find local replica set configuration document at startup;  NoMatchingDocument: Did not find replica set configuration document in local.system.replset
2019-10-02T12:16:22.778+0000 I CONTROL  [LogicalSessionCacheRefresh] Sessions collection is not set up; waiting until next sessions refresh interval: Replication has not yet been configured
2019-10-02T12:16:22.778+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
2019-10-02T12:16:22.778+0000 I CONTROL  [LogicalSessionCacheReap] Sessions collection is not set up; waiting until next sessions reap interval: config.system.sessions does not exist
2019-10-02T12:16:34.619+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:45800 #1 (1 connection now open)
2019-10-02T12:16:34.619+0000 I NETWORK  [conn1] received client metadata from 127.0.0.1:45800 conn1: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.0.12" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 9 (stretch)"", architecture: "x86_64", version: "Kernel 4.14.146-119.123.amzn2.x86_64" } }
2019-10-02T12:16:34.622+0000 I NETWORK  [conn1] end connection 127.0.0.1:45800 (0 connections now open)
2019-10-02T12:16:34.881+0000 I NETWORK  [listener] connection accepted from 10.114.18.171:54230 #2 (1 connection now open)
2019-10-02T12:16:34.882+0000 I NETWORK  [conn2] end connection 10.114.18.171:54230 (0 connections now open)
2019-10-02T12:16:34.928+0000 I NETWORK  [listener] connection accepted from 10.114.18.171:54232 #3 (1 connection now open)
2019-10-02T12:16:34.948+0000 I NETWORK  [conn3] received client metadata from 10.114.18.171:54232 conn3: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.0.12" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 9 (stretch)"", architecture: "x86_64", version: "Kernel 4.14.146-119.123.amzn2.x86_64" } }
2019-10-02T12:16:34.948+0000 I ACCESS   [conn3] Supported SASL mechanisms requested for unknown user 'root@admin'
2019-10-02T12:16:34.949+0000 I ACCESS   [conn3] SASL SCRAM-SHA-1 authentication failed for root on admin from client 10.114.18.171:54232 ; UserNotFound: Could not find user root@admin
```
The primary and secondary logs show the same information. 

My root password is set as **admin** by the way. I noticed in the primary logs, its not finding and creating the  local replica set configuration and the SCRAM-SHA-1 authentication is failing for root on admin from the client because it cannot find the user root@admin

**Comment by miguelaeh** [comment]
Hi @kwill4026 ,
In your configma from previous comments you have this:
```
data:
  mongodb-password: ZnJhbms=
  mongodb-replica-set-key: MWYyZDFlMmU2N2Rm
  mongodb-root-password: YWRtaW4=
  mongodbDatabase: dGV4dA==
  mongodbUsername: ZnJlZA==
```

Are you deploying in the same way?

Also, be sure you deleted the PVCs before redeploy to remove stored password and so on.

**Comment by kwill4026** [comment]
@miguelaeh in the previous comment that was not in my configmap. Those values were the secrets I generated to serve as the existing secrets due to the bug you mentioned. And I made sure to comment out the **keyfile** parameter in the configmap section of the values.yaml
Also I always make sure I am deleting the PVC's when redeploying. I usually delete with
helm delete test --purge; kubectl delete pvc -l app=mongodb 
```
[X.X.X.X ]$ kubectl get secrets mongosecrets -o yaml
apiVersion: v1
data:
  mongodb-password: ZnJhbms=
  mongodb-replica-set-key: MWYyZDFlMmU2N2Rm
  mongodb-root-password: YWRtaW4=
  mongodbDatabase: dGV4dA==
  mongodbUsername: ZnJlZA==
kind: Secret
metadata:
  creationTimestamp: "2019-10-01T17:15:54Z"
  name: mongosecrets
  namespace: default
  resourceVersion: "1727119"
  selfLink: /api/v1/namespaces/default/secrets/mongosecrets
  uid: 202afb6a-e46f-11e9-ab3d-0a40a152b37a
type: Opaque
```

**Comment by miguelaeh** [comment]
Hi @kwill4026 ,
Try to see if the user user and password are actually `admin`:`admin` you can decode the secret with `base64` to see if it match or not.

**Comment by kwill4026** [comment]
@miguelaeh still didnt work

**Comment by miguelaeh** [comment]
Did you check the user and password? Do they match with the one you configured?

**Comment by kwill4026** [comment]
@miguelaeh yes

**Comment by kwill4026** [comment]
i also tried with creating a resource name {{- template "mongodb.fullname" . -}}-keyfile
in which it contains:
```
{{ if and .Values.usePassword (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mongodb.fullname" . }}-keyfile
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.replicaSet.enabled }}
  {{- if .Values.replicaSet.key }}
  mongodb-replica-set-key:  {{ .Values.replicaSet.key | b64enc | quote }}
  {{- else }}
  mongodb-replica-set-key: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
```

still the same issue where the pods start running then crash. Its mostly because for some weird reason the primary is unable to locate and create a replica set, as I can see this logged in the primary pod.

```
[X.X.X.X.@mongodb]$ kubectl logs pod/test-mongodb-arbiter-0
 13:35:48.64 INFO  ==> ** Starting MongoDB setup **
 13:35:48.66 INFO  ==> Validating settings in MONGODB_* env vars...
 13:35:48.66 INFO  ==> Initializing MongoDB...
 13:35:48.67 INFO  ==> Deploying MongoDB from scratch...
 13:35:48.67 INFO  ==> Custom configuration /opt/bitnami/mongodb/conf/mongodb.conf detected!
 13:35:49.35 INFO  ==> Creating users...
 13:35:49.35 INFO  ==> Users created
 13:35:49.35 INFO  ==> Writing keyfile for replica set authentication: ymeH2L33AM /opt/bitnami/mongodb/conf/keyfile
 13:35:49.35 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 13:35:49.35 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 13:35:49.36 INFO  ==> Configuring MongoDB replica set...
 13:35:49.36 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 13:35:49.36 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 13:35:49.36 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 13:35:49.36 INFO  ==> Stopping MongoDB...
 13:35:51.36 INFO  ==> Trying to connect to MongoDB server...
 13:35:51.41 INFO  ==> Found MongoDB server listening at test-mongodb:27017 !
```


```
[X.X.X.X mongodb]$ kubectl logs pod/test-mongodb-primary-0

 13:32:38.74 INFO  ==> ** Starting MongoDB setup **
 13:32:38.75 INFO  ==> Validating settings in MONGODB_* env vars...
 13:32:38.75 INFO  ==> Initializing MongoDB...
 13:32:38.76 INFO  ==> Deploying MongoDB with persisted data...
 13:32:38.76 INFO  ==> Custom configuration /opt/bitnami/mongodb/conf/mongodb.conf detected!
 13:32:38.76 INFO  ==> Writing keyfile for replica set authentication: ymeH2L33AM /opt/bitnami/mongodb/conf/keyfile
 13:32:38.76 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 13:32:38.77 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 13:32:38.77 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 13:32:38.77 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 13:32:38.77 WARN  ==> "/opt/bitnami/mongodb/conf/mongodb.conf" is not writable by current user. Skipping modifications...
 13:32:38.77 INFO  ==> 
 13:32:38.77 INFO  ==> ########################################################################
 13:32:38.77 INFO  ==>  Installation parameters for MongoDB:
 13:32:38.77 INFO  ==>    Persisted data and properties have been restored.
 13:32:38.77 INFO  ==>    Any input specified will not take effect.
 13:32:38.77 INFO  ==> (Passwords are not shown for security reasons)
 13:32:38.78 INFO  ==> ########################################################################
 13:32:38.78 INFO  ==> 
 13:32:38.78 INFO  ==> Loading custom scripts...
find: '/docker-entrypoint-initdb.d/': No such file or directory
 13:32:38.78 INFO  ==> ** MongoDB setup finished! **

 13:32:38.79 INFO  ==> ** Starting MongoDB **
2019-10-09T13:32:38.807+0000 I STORAGE  [main] Max cache overflow file size custom option: 0
2019-10-09T13:32:38.807+0000 I CONTROL  [main] ***** SERVER RESTARTED *****
2019-10-09T13:32:38.809+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2019-10-09T13:32:38.811+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/bitnami/mongodb/data/db 64-bit host=test-mongodb-primary-0
2019-10-09T13:32:38.812+0000 I CONTROL  [initandlisten] db version v4.0.12
2019-10-09T13:32:38.812+0000 I CONTROL  [initandlisten] git version: 5776e3cbf9e7afe86e6b29e22520ffb6766e95d4
2019-10-09T13:32:38.812+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
2019-10-09T13:32:38.812+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2019-10-09T13:32:38.812+0000 I CONTROL  [initandlisten] modules: none
2019-10-09T13:32:38.812+0000 I CONTROL  [initandlisten] build environment:
2019-10-09T13:32:38.812+0000 I CONTROL  [initandlisten]     distmod: debian92
2019-10-09T13:32:38.812+0000 I CONTROL  [initandlisten]     distarch: x86_64
2019-10-09T13:32:38.812+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2019-10-09T13:32:38.812+0000 I CONTROL  [initandlisten] options: { config: "/opt/bitnami/mongodb/conf/mongodb.conf", net: { bindIpAll: true, ipv6: false, port: 27017, unixDomainSocket: { enabled: true, pathPrefix: "/opt/bitnami/mongodb/tmp" } }, processManagement: { fork: false, pidFilePath: "/opt/bitnami/mongodb/tmp/mongodb.pid" }, replication: { enableMajorityReadConcern: true, replSetName: "rs0" }, security: { authorization: "enabled" }, setParameter: { enableLocalhostAuthBypass: "false" }, storage: { dbPath: "/bitnami/mongodb/data/db", directoryPerDB: false, journal: { enabled: true } }, systemLog: { destination: "file", logAppend: true, logRotate: "reopen", path: "/opt/bitnami/mongodb/logs/mongodb.log", quiet: false, verbosity: 0 } }
2019-10-09T13:32:38.812+0000 I STORAGE  [initandlisten] Detected data files in /bitnami/mongodb/data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2019-10-09T13:32:38.812+0000 I STORAGE  [initandlisten] 
2019-10-09T13:32:38.812+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2019-10-09T13:32:38.812+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2019-10-09T13:32:38.812+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3328M,cache_overflow=(file_max=0M),session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2019-10-09T13:32:39.492+0000 I STORAGE  [initandlisten] WiredTiger message [1570627959:492378][1:0x7f54a87f5080], txn-recover: Main recovery loop: starting at 1/22400 to 2/256
2019-10-09T13:32:39.578+0000 I STORAGE  [initandlisten] WiredTiger message [1570627959:578580][1:0x7f54a87f5080], txn-recover: Recovering log 1 through 2
2019-10-09T13:32:39.631+0000 I STORAGE  [initandlisten] WiredTiger message [1570627959:631787][1:0x7f54a87f5080], txn-recover: Recovering log 2 through 2
2019-10-09T13:32:39.674+0000 I STORAGE  [initandlisten] WiredTiger message [1570627959:674597][1:0x7f54a87f5080], txn-recover: Set global recovery timestamp: 0
2019-10-09T13:32:39.687+0000 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
2019-10-09T13:32:39.704+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/bitnami/mongodb/data/db/diagnostic.data'
2019-10-09T13:32:39.707+0000 I REPL     [initandlisten] Did not find local initialized voted for document at startup.
2019-10-09T13:32:39.707+0000 I REPL     [initandlisten] Rollback ID is 1
2019-10-09T13:32:39.707+0000 I REPL     [initandlisten] Did not find local replica set configuration document at startup;  NoMatchingDocument: Did not find replica set configuration document in local.system.replset
2019-10-09T13:32:39.707+0000 I CONTROL  [LogicalSessionCacheRefresh] Sessions collection is not set up; waiting until next sessions refresh interval: Replication has not yet been configured
2019-10-09T13:32:39.707+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
2019-10-09T13:32:39.708+0000 I CONTROL  [LogicalSessionCacheReap] Sessions collection is not set up; waiting until next sessions reap interval: config.system.sessions does not exist
2019-10-09T13:32:49.020+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:53230 #1 (1 connection now open)
2019-10-09T13:32:49.020+0000 I NETWORK  [conn1] received client metadata from 127.0.0.1:53230 conn1: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.0.12" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 9 (stretch)"", architecture: "x86_64", version: "Kernel 4.14.146-119.123.amzn2.x86_64" } }
2019-10-09T13:32:49.023+0000 I NETWORK  [conn1] end connection 127.0.0.1:53230 (0 connections now open)
2019-10-09T13:32:49.502+0000 I NETWORK  [listener] connection accepted from 10.114.18.232:56264 #2 (1 connection now open)
2019-10-09T13:32:49.502+0000 I NETWORK  [conn2] end connection 10.114.18.232:56264 (0 connections now open)
2019-10-09T13:32:49.547+0000 I NETWORK  [listener] connection accepted from 10.114.18.232:56266 #3 (1 connection now open)
2019-10-09T13:32:49.565+0000 I NETWORK  [conn3] received client metadata from 10.114.18.232:56266 conn3: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.0.12" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 9 (stretch)"", architecture: "x86_64", version: "Kernel 4.14.146-119.123.amzn2.x86_64" } }
2019-10-09T13:32:49.565+0000 I ACCESS   [conn3] Supported SASL mechanisms requested for unknown user 'root@admin'
2019-10-09T13:32:49.565+0000 I ACCESS   [conn3] SASL SCRAM-SHA-1 authentication failed for root on admin from client 10.114.18.232:56266 ; UserNotFound: Could not find user root@admin

**Comment by miguelaeh** [comment]
Hi @kwill4026 ,
If MongoDB is trying to write into `mongodb.conf` that is mounted as a ConfigMap it will always fails as a ConfiMap is not writable. Maybe we should try with another approach instead of a ConfigMap.

**Comment by kwill4026** [comment]
@miguelaeh this is true, there could be another option to approach with. And I have definitely seen other helm charts in which the configmap was writable such as [mongodb-replicaset helm chart](https://github.com/helm/charts/tree/master/stable/mongodb-replicaset) which can still use the configmap and utilize initContainers to copy an empty mongo conf config file to a new directory so that when a entry gets added via the configmap configuration value, it
will then be mounted to a new mongo conf path in the directory. By default when ran, their chart creates an empty config file even with the database set as a replicaset. When the user adds mongod conf entries to the configmap section, thats when it copies that configmap to a volumeMount which from the initContainer instructions, it will copy that to a volume created in the initContainer which then gets copied and mounted to a volumeMount. This way when I bash into the container I can see that the pod has applied the mongodb conf settings. 
Is this something this chart will be able to achieve?

Similar to how you all have the volumePermissions container, I would think this would work in which we could do one for the mongodb conf file in which for both the statefulset-primary-rs.yaml and statefulset-secondary-rs.yaml will include a initContainer for this. Since there is already a volumeMount for the mongo conf file located at /opt/bitnami/mongodb/conf/mongodb.conf versus an empty conf file, I am not sure how to approach that. But if it was empty beforehand I would suggest something like this:

```
 initContainers:
      {{- if .Values.extraInitContainers }}
{{ tpl .Values.extraInitContainers . | indent 6}}
      {{- end }}
      - name: copy-config
        image: {{ template "mongodb.volumePermissions.image" . }}
        imagePullPolicy: {{ .Values.volumePermissions.image.pullPolicy | quote }}
        command: ["cp /configdb-readOnly/mongodb.conf /data/configdb/mongodb.conf"]
        volumeMounts:
        - name: config
          mountPath: /configdb-readonly
        - name: configdir 
          mountPath: /data/configdb
 containers:
     - name: {{ template "mongodb.name" . }}-primary
       image: {{ template "mongodb.image" . }}
       imagePullPolicy: {{ .Values.image.pullPolicy }}
                                 .
                                 .
                                 .
       volumeMounts: 
           - name: configdir
             mountPath: /data/configdb

                                  .
                                  . 
                                  .
 volumes: 
     - name: config 
        configMap: 
            name: {{ template "mongodb.fullname" . }}
     - name:  configdir
        emptyDir: {}

 ```

**Comment by miguelaeh** [comment]
Hi @kwill4026 ,
We are working on change the image to try to address this problem. We will update the thread when we have news.
Thank you very much for reporting!

**Comment by javsalgar** [comment]
Hi,

Just wanting to add my 2 cents to this. In my opinion I see a conflict with the pods initialization and wanting to include your own configuration. In the initialization, we need to modify the configuration for setting up the cluster, and if we don't modify the configmap, then it is likely that the initialization would fail. 

For including ca.crt and other elements, you could use the extraVolumes and extraVolumeMounts sections to add a secret with you certificates. With respect to adding your custom configuration, could you let me know if this makes sense (sorry if you already tried before).

1) Deploy the chart with the default settings (i.e. not adding a configmap)
2) Once it is initialized, then execute helm upgrade, this time using your configuration and your extraVolumes (with the CA for example)

Would that work for your case?

**Comment by kwill4026** [comment]
Hello @javsalgar  I tried this just now and still no luck. I modified my charts to create its own CA (mongodb.crt) and sign pem files for each primary and secondary (mongodb.pem) and place them into a volume I created in the pod. I have an initdb script that generates the root CA upon installing the chart and at the same time signs the pem files. I tried deploying the chart with default settings (no configmap, watched it load and run fine, uncommented the "configuration" section in the values.yaml, ran a helm upgrade and watched the pods create fine. 
Now this time I did the same, with deploying the chart with default settings, then I instead added the appropriate tls settings in the configuration section to include net.tls.mode, net.tls.CAFile, net.tls.certificateKeyFile. They of course contain my CA and pem file  which was created and stored in the volume mount. Once I do the helm upgrade it crashes the pod and looking at the logs seem to show it getting stuck at the configuration file. 
```
mongodb 17:05:13.02 INFO  ==> Deploying MongoDB with persisted data...
mongodb 17:05:13.02 INFO  ==> Writing keyfile for replica set authentication...
mongodb 17:05:13.03 INFO  ==> Loading custom scripts...
mongodb 17:05:13.03 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
```

I even tried setting the tls settings through the --extraFlags setting. It was able to take several flags such as 
```
extraFlags:
  - "--wiredTigerCacheSizeGB=2"
  - "--syncdelay=55
```

but could not take

extraFlags:
   - "--tlsMode=preferSSL"
   - "--tlscertificateKeyFile=/pem-dir/mongodb.pem"
   - "--tlsCAFile=/certificates/mongodb-cacert"

For some reason this mongodb helm chart does not take in the ssl/tls settings but will take other mongod conf settings. why is this. 
I can send you my entire chart setup in a zip file if needed to test on your end. I really would like to get this TLS encryption setup going.

**Comment by javsalgar** [comment]
Hi,

What's the exact error that it shows? If it only shows the logs above, could you try running setting the `image.debug=ture` value?

**Comment by kwill4026** [comment]
I was able to get more information on this. I am going to close this and open another case on this for better clarification

**Comment by chaoshengit** [comment]
Hello @miguelaeh，I still can not use my custom configmap settings for replicaset.

The chart version: mongodb-10.20.5
mongodb version: 4.4.6

The way I deployed mongodb replica:
1. I created a configmap named mongodb and deployed by: helm install mongodb ./mongodb --set existingConfigmap=mongodb -n test 
the content in the configmap:
apiVersion: v1
data:
  mongodb.conf: |
    storage:
      dbPath: /bitnami/chaoshen/data/db
      journal:
        enabled: true
      directoryPerDB: false
    # where to write logging data.
    systemLog:
      destination: file
      quiet: false
      logAppend: true
      logRotate: reopen
      path: /bitnami/chaoshen/logs/mongodb.log
      verbosity: 0
    # network interfaces
    net:
      port: 27017
      unixDomainSocket:
        enabled: true
        pathPrefix: /bitnami/chaoshen/tmp
      ipv6: false
      bindIpAll: true
      #bindIp:
    # replica set options
    replication:
      replSetName: rs0
      enableMajorityReadConcern: true
    # sharding options
    #sharding:
      #clusterRole:
    # process management options
    processManagement:
       fork: false
       pidFilePath: /bitnami/chaoshen/tmp/mongodb.pid
    # set parameter options
    setParameter:
       enableLocalhostAuthBypass: false
    # security options
    security:
      authorization: enabled
      keyFile: /bitnami/chaoshen/conf/keyfile
kind: ConfigMap
note：I have aleardy create the dirs: /bitnami/chaoshen，/bitnami/chaoshen/tmp ,etc by edit the scripts-configmap.yaml
2. I configured the "configuration" in values.yaml directly,then exec: helm install mongodb ./mongodb -n test
The content in "configuration" was same with the content in configmap.

And I got constant CrashLoopBackOff with the following logs:
root@172-21-92-10:/opt/mongodb_charts# kubectl logs -f pod/mongodb-0 -n test
Advertised Hostname: mongodb-0.mongodb-headless.test.svc.cluster.local
Pod name matches initial primary pod name, configuring node as a primary
mongodb 06:03:14.94
mongodb 06:03:14.94 Welcome to the Bitnami mongodb container
mongodb 06:03:14.94 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 06:03:14.94 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 06:03:14.95
mongodb 06:03:14.95 INFO  ==> ** Starting MongoDB setup **
mongodb 06:03:14.97 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 06:03:15.00 INFO  ==> Initializing MongoDB...
mongodb 06:03:15.01 INFO  ==> Deploying MongoDB from scratch...
----------------------------------------------------------------------------------------------
Please give me some advice about this.

**Comment by rafariossaa** [comment]
Hi @chaoshengit ,
  I think you issue is not related with the original in this thread, do you mind opening a new one ? This way it would be easier to help you with your issue.
  Regarding your issue, could you enable debug and see if it provide more information in the log ?
