### ISSUE TITLE
Podman - Failed global initialization: FileNotOpen: Failed to open "/opt/bitnami/mongodb/logs/mongodb.log"

### ISSUE THREAD

**Issue by nccurry** [bitnami/bitnami-docker-mongodb#205]
**Description**

MongoDB fails to start when running with podman on Fedora CoreOS.

```
2020-03-31T19:27:56.409+0000 F CONTROL  [main] Failed global initialization: FileNotOpen: Failed to open "/opt/bitnami/mongodb/logs/mongodb.log"
```

**Steps to reproduce the issue:**

1. Deploy Fedora CoreOS host
2. Try to deploy image

**Describe the results you received:**
```
[root@fcos ~]# /usr/bin/podman run -p 27017:27017 -e MONGODB_USERNAME=user -e MONGODB_PASSWORD=password -e MONGODB_DATABASE=database -e MONGODB_SYSTEM_LOG_VERBOSITY=5 -e MONGODB_ROOT_PASSWORD=passwordrootmongodb  bitnami/mongodb:latest                                                               19:27:54.58 
 19:27:54.58 Welcome to the Bitnami mongodb container
 19:27:54.59 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
 19:27:54.59 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
 19:27:54.59 Send us your feedback at containers@bitnami.com
 19:27:54.59 
 19:27:54.59 INFO  ==> ** Starting MongoDB setup **
 19:27:54.60 INFO  ==> Validating settings in MONGODB_* env vars...
 19:27:54.60 INFO  ==> Initializing MongoDB...
 19:27:54.60 INFO  ==> No injected configuration files found. Creating default config files...
 19:27:54.60 INFO  ==> Deploying MongoDB from scratch...
 19:27:55.08 INFO  ==> Creating users...
 19:27:55.08 INFO  ==> Creating root user...
 19:27:55.22 INFO  ==> Creating 'user' user...
 19:27:55.32 INFO  ==> Users created
 19:27:55.32 INFO  ==> Stopping MongoDB...
 19:27:56.34 INFO  ==> Enabling authentication...
 19:27:56.36 INFO  ==> 
 19:27:56.36 INFO  ==> ########################################################################
 19:27:56.36 INFO  ==>  Installation parameters for MongoDB:
 19:27:56.37 INFO  ==>   User Name: user
 19:27:56.37 INFO  ==>   Password: **********
 19:27:56.37 INFO  ==>   Database: database
 19:27:56.37 INFO  ==> (Passwords are not shown for security reasons)
 19:27:56.37 INFO  ==> ########################################################################
 19:27:56.37 INFO  ==> 
 19:27:56.38 INFO  ==> Loading custom scripts...
find: '/docker-entrypoint-initdb.d/': No such file or directory
 19:27:56.38 INFO  ==> ** MongoDB setup finished! **

 19:27:56.39 INFO  ==> ** Starting MongoDB **
2020-03-31T19:27:56.409+0000 F CONTROL  [main] Failed global initialization: FileNotOpen: Failed to open "/opt/bitnami/mongodb/logs/mongodb.log"
```

**Describe the results you expected:**

Running container image

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
[root@fcos ~]# podman version
Version:            1.8.1
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64
```

- Output of `docker info`:

```
[root@fcos ~]# podman info
host:
  BuildahVersion: 1.14.2
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.10-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.10, commit: 6b526d9888abb86b9e7de7dfdeec0da98ad32ee0'
  Distribution:
    distribution: fedora
    version: "31"
  MemFree: 1177010176
  MemTotal: 2077835264
  OCIRuntime:
    name: crun
    package: crun-0.12.2.1-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.12.2.1
      commit: cd7cea7114db5f6aa35fbb69fa307c19c2728a31
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 1
  eventlogger: journald
  hostname: fcos
  kernel: 5.5.8-200.fc31.x86_64
  os: linux
  rootless: false
  uptime: 2h 26m 37.4s (Approximately 0.08 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 13
  GraphDriverName: overlay
  GraphOptions:
    overlay.mountopt: nodev,metacopy=on
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 3
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

QEMU/KVM on Fedora 31 host

**Comment by nccurry** [comment]
Opened issue in Fedora CoreOS issue tracker as well:
https://github.com/coreos/fedora-coreos-tracker/issues/444

**Comment by Mauraza** [comment]
Hi @nccurry,

I haven't been able to reproduce it. Let's see the answer to the issue you put in CoreOS.

**Comment by nccurry** [comment]
This problem is resolved in newer version of Fedora CoreOS.

**Comment by lucab** [comment]
Yes, I think it's an issue with the underlying runtime, this can be safely closed.

**Comment by nicolasparada** [comment]
Still seeing this issue on Ubuntu on Windows Subsystem for Linux.

**Comment by javsalgar** [comment]
Hi,

I suppose that, just like it happened before, it is a specific issue of that platform. I would let the Windows Subsystem for Linux devs know in case there's something they can do.

**Comment by ttorac** [comment]
I am having the same problem trying to config mongo on windows... I think it might be a mongo bug

**Comment by javsalgar** [comment]
Hi,

Do you mean a bug in the MongoDB code?, then it may be worth reporting it to the MongoDB devs. However, I'm not sure if they officially support WSL.

**Comment by krimpenrik** [comment]
I am having this issue with WSL2 docker - bitnami / mongo when trying to run as user root,

**Comment by carrodher** [comment]
According to the previous comments it seems this is not an issue in the bitnami-docker-mongodb image but in the platform itself, can you try using the latest version?

**Comment by nicolasparada** [comment]
Forgot to comment on this. Doing and upgrade of my WSL environment did fix the issue 👍
So yeah, the issue is on the platform.
